### ISSUE TITLE
V-Model does not work and you provide no example of it working

### ISSUE THREAD

**Issue by moodyVlad** [coding-wisely/vue-tailwind-datepicker#1]

**Comment by svnindia** [comment]
@moodyVlad 

we have to use the `input` event listener  

Example : 

```
  <vue-tailwind-datepicker @input="setDate"></vue-tailwind-datepicker>

.
.
.
methods: {
  setDate(date) {
    this.form.mydate = date;
  }
}
```

Reference :

 https://github.com/coding-wisely/vue-tailwind-datepicker/blob/master/src/vue-tailwind-datepicker.vue#L87

https://vuejs.org/v2/guide/components-custom-events.html

**Comment by Sharvadze** [comment]
Is there a way to close the calendar popup when the date is selected?

**Comment by nezaboravi** [comment]
> Is there a way to close the calendar popup when the date is selected?

Hey @Sharvadze , it is now, i have updated the code. 
```
<datepicker inline-template
                selected-day-class="bg-teal-300"
                :close-on-click="true"
                input-field-class="bg-green-200 h-12 focus:outline-none w-full border-b border-grey-500"
                date-format="YYYY-MM-DD">
    </datepicker>
```

Please note `close-on-click` property

**Comment by nezaboravi** [comment]
Provided example of using @input on README file
Added close-on-click on day selected.
