### ISSUE TITLE
Format date doesn't persist

### ISSUE THREAD

**Issue by joantp** [coding-wisely/vue-tailwind-datepicker#2]
I configure "DD-MM-YY" as format date, and it'is ok at creating the component. But when I select a new date, it appears as default format "YY-MM-DD". How can I make format persist?

**Comment by nezaboravi** [comment]
Thank you for reporting the issue and sorry for late reply, lack of time on my side. I will have a look into this and let you know one of these days @joantp

**Comment by nezaboravi** [comment]
@joantp please upgrade package and try. Works on my side now.
