### ISSUE TITLE
WARNING export 'VueTailwindDatepicker' was not found in '@coding-wisely/vue-tailwind-datepicker'

### ISSUE THREAD

**Issue by blestab** [coding-wisely/vue-tailwind-datepicker#4]
I have just installed this plugin into my vue project

`npm install @coding-wisely/vue-tailwind-datepicker
`

and adding it to my component inside the script tag:

`import { VueTailwindDatepicker } from '@coding-wisely/vue-tailwind-datepicker'
`

and then in my template

```
                        <vue-tailwind-datepicker
                        v-model="userData.date_of_birth"
                        @input="(v) => userData.date_of_birth = v">
                        </vue-tailwind-datepicker>

```
I get his warning when compiling my project:
 
```
WARNING  Compiled with 1 warnings                                                                                                7:34:31 PM
 warning  in ./src/views/patients/new.vue?vue&type=script&lang=js&

"export 'VueTailwindDatepicker' was not found in '@coding-wisely/vue-tailwind-datepicker'
```

and when i try to access my form that uses the plugin, i notice this error in the console:

`vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <vue-tailwind-datepicker> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
`

**Comment by nezaboravi** [comment]
Please try :
import VueTailwindDatepicker  from '@coding-wisely/vue-tailwind-datepicker'

in your component add components: { VueTailwindDatepicker},
